# appium api
# - https://appium.github.io/appium/docs/en/2.0/reference/commands/appium_base_driver-1._appium_base_driver/

@BASE_URL=http://localhost:4723

#
# get current server status
#
GET {{BASE_URL}}/status
###

#
# create ios session
#
# @name ios_session
POST {{BASE_URL}}/session HTTP/1.1
content-type: application/json

{
  "capabilities": {
    "alwaysMatch": {
      "platformName": "iOS",
      "appium:deviceName": "iPhone 15 Pro",
      "appium:platformVersion": "17.0",
      "appium:orientation": "PORTRAIT",
      "appium:automationName": "XCUITest",
      "appium:newCommandTimeout": 240
    },
    "firstMatch": [{}]
  }
}
###

#@ios_session_id = {{ios_session.response.body.value.sessionId}}

#
# get all sessions
# @name get_sessions
GET {{BASE_URL}}/sessions
###
@ios_session_id = {{get_sessions.response.body.value[0].id}}

#
# get session info
#
GET {{BASE_URL}}/session/{{ios_session_id}}
###

#
# get source
#
GET {{BASE_URL}}/session/{{ios_session_id}}/source
###

#
# get event list
#
POST {{BASE_URL}}/session/{{ios_session_id}}/appium/events
###

#
# get context
#
GET {{BASE_URL}}/session/{{ios_session_id}}/context
###

#
# get settings
#
GET {{BASE_URL}}/session/{{ios_session_id}}/appium/settings
###

#
# get log (syslog, crashlog, performance, server, safariConsole, safariNetwork)
#
GET {{BASE_URL}}/session/{{ios_session_id}}/log/types
###
POST {{BASE_URL}}/session/{{ios_session_id}}/log

{ "type": "syslog" }
###

#
# get timeouts
#
GET {{BASE_URL}}/session/{{ios_session_id}}/timeouts
###

#
# find elements
#
POST {{BASE_URL}}/session/{{ios_session_id}}/elements

{"using":"*", "value":"*"}
###

#
# find a element
# @name find_ios_element
POST {{BASE_URL}}/session/{{ios_session_id}}/element

{"using":"accessibility id", "value":"body-text"}
###

@found_ios_element = {{find_ios_element.response.body.value.ELEMENT}}

#
# get text
#
GET {{BASE_URL}}/session/{{ios_session_id}}/element/{{found_ios_element}}/text
###

#
# send actions(touch-down)
#
POST {{BASE_URL}}/session/{{ios_session_id}}/actions

{"actions":[{"type":"pointer","id":"pointer1","parameters":{"pointerType":"touch"},"actions":[{"type":"pointerMove","x":138,"y":248,"duration":0},{"type":"pointerDown","button":0},{"type":"pointerMove","x":134,"y":447,"duration":8},{"type":"pointerUp","button":0}]}]}
###

#
# send actions(touch-up)
#
POST {{BASE_URL}}/session/{{ios_session_id}}/actions

{"actions":[{"type":"pointer","id":"pointer1","parameters":{"pointerType":"touch"},"actions":[{"type":"pointerMove","x":128,"y":441,"duration":0},{"type":"pointerDown","button":0},{"type":"pointerMove","x":130,"y":238,"duration":8},{"type":"pointerUp","button":0}]}]}
###

#
# execute script
#
POST {{BASE_URL}}/session/{{ios_session_id}}/appium/execute_driver

{"script": "const ele = await driver.$('~show-detail-view-button'); await ele.click()", "type": "webdriverio", "timeout": 10000}
###

#
# execute script
#
POST {{BASE_URL}}/session/{{ios_session_id}}/appium/execute_driver

{"script": "await driver.touchAction({action: 'tap', x: 129, y: 123})"}
###

#
# delete session
#
DELETE {{BASE_URL}}/session/{{ios_session_id}}
###
